### ISSUE TITLE
Can you please make the Readme more informative?

### ISSUE THREAD

**Issue by lemccomb** [timfallmk/github-changelog-generator-action#1]
I was considering using this action to generate changelogs in my repo, but I can't tell anything about how it works or what kind of changelog it creates.
If I use this, do I need to for format my commit messages any particular way?
Do you have an example of how to use this in a workflow?
What does the resulting changelog look like?

**Comment by timfallmk** [comment]
Apologies. I wrote this for my own purposes a long time ago and haven't looked at it in quite some time. It's essentially an automated wrapper for https://github.com/github-changelog-generator/github-changelog-generator, so any details you need should be there.

tl;dr You shouldn't need to format your commits in any special way iirc.
